FROM python:3.11

WORKDIR /app
ENV FLASK_APP="app:app"
ADD app /app
ADD Pipfile.lock /app
RUN pip install pipenv
RUN pipenv sync

CMD ["pipenv", "run", "python", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000"]
