FROM python:3.11

WORKDIR /app

ENV PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
ENV FLASK_APP="app:app"

ADD pyproject.toml /app

ADD app /app
RUN pip install poetry
RUN poetry install --no-root

CMD ["poetry", "run", "python", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000"]
