# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        tool: [pipenv, poetry]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set week of the year in environment variable
      run: echo "WEEK=$(date +%Y%W)" >> ${GITHUB_ENV}
    - name: print env variables
      run: env
    - uses: actions/cache@v3  # think about the planet please
      with:
        path: ~/.cache/pip
        key: ${{env.WEEK}}
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip ${{ matrix.tool }}
    - name: Test the build
      run: |
        bash test.sh ${{ matrix.tool }}
